---
# ServiceAccount, Role, and RoleBinding are hooks that run BEFORE the cleanup Job
# They have a higher weight (lower number) so they execute first
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.subscription.name }}-cleanup
  namespace: {{ .Values.subscription.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.subscription.name }}-cleanup
  namespace: {{ .Values.subscription.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - subscriptions
  verbs:
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.subscription.name }}-cleanup
  namespace: {{ .Values.subscription.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.subscription.name }}-cleanup
subjects:
- kind: ServiceAccount
  name: {{ .Values.subscription.name }}-cleanup
  namespace: {{ .Values.subscription.namespace }}
---
# Job is a hook that runs AFTER RBAC resources are created (lower weight = runs later)
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.subscription.name }}-cleanup-{{ .Release.Revision }}
  namespace: {{ .Values.subscription.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  activeDeadlineSeconds: 30
  ttlSecondsAfterFinished: 0
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: {{ .Values.subscription.name }}-cleanup
      restartPolicy: Never
      containers:
      - name: cleanup
        image: quay.io/openshift/origin-cli:latest
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Checking for orphaned CSVs and cleaning up if needed..."
          
          # Check if subscription exists
          if oc get subscription {{ .Values.subscription.name }} -n {{ .Values.subscription.namespace }} &>/dev/null; then
            echo "Subscription exists. Deleting it to allow clean reinstall..."
            oc delete subscription {{ .Values.subscription.name }} -n {{ .Values.subscription.namespace }} --ignore-not-found || true
            sleep 2
          fi
          
          # Get all CSVs for cloud-native-postgresql that are not referenced
          # jsonpath doesn't support regex, so we get all CSVs and filter in bash
          CSVS=$(oc get csv -n {{ .Values.subscription.namespace }} -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' 2>/dev/null | grep "^cloud-native-postgresql" || true)
          
          if [ -n "$CSVS" ]; then
            echo "Found CSVs: $CSVS"
            echo "Deleting orphaned CSVs..."
            for CSV in $CSVS; do
              echo "Deleting CSV: $CSV"
              oc delete csv "$CSV" -n {{ .Values.subscription.namespace }} --ignore-not-found || true
            done
            sleep 2
          else
            echo "No CSVs found."
          fi
          
          echo "Cleanup completed successfully."
          exit 0
